### PR TITLE
Creates files for uploading to pypi

### LINKED ISSUE #41: PyPi package support
The files to create a pypi package and publish so we can official promote that tool.

### PR DESCRIPTION
**Pull request by Yagueteiro**
Closes #41

*NOTE:* In the setup.py, I've set some placeholders.

### CODE REVIEW

**Comment by Mte90** [comment]
I don't have access to fix that branch so I cannot merge for the conflict.

**Comment by Yagueteiro** [comment]
I think you can now

**Comment by Mte90** [comment]
I am getting some issues on merging can you check on your side for the conflicts?

**Comment by Mte90** [comment]
Thanks a lot!

**Pull request merged**
